version: '3.4'

services:

  catalogdb:
    image: mongo
  mongoclient:
    image: mongoclient/mongoclient
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: redis:alpine
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  discountdb:
    image: postgres
  pgadmin:
    image: dpage/pgadmin4

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  portainer:
    image: portainer/portainer-ce

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine