version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - "c:\\data\\catalogdb:/data/db"
  mongoclient:
    container_name: mongoclient
    #restart: always
    ports:
       - "8005:3000"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
  
  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"
