version: '3.4'

services:

  catalogdb:
    image: mongo
  mongoclient:
    image: mongoclient/mongoclient
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: redis:alpine
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  portainer:
    image: portainer/portainer-ce